/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// AgencyCommission
    /// </summary>
    [DataContract]
    public partial class AgencyCommission :  IEquatable<AgencyCommission>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgencyCommission" /> class.
        /// </summary>
        /// <param name="commissionTime">Commission Time. (unix timestamp)..</param>
        /// <param name="userId">User ID..</param>
        /// <param name="groupName">Group name..</param>
        /// <param name="commissionAmount">Commission Amount..</param>
        /// <param name="commissionAsset">Commission Asset..</param>
        /// <param name="source">Source. SPOT - SPOT Rebate, FUTURES - Futures Rebate..</param>
        public AgencyCommission(long commissionTime = default(long), long userId = default(long), string groupName = default(string), string commissionAmount = default(string), string commissionAsset = default(string), string source = default(string))
        {
            this.CommissionTime = commissionTime;
            this.UserId = userId;
            this.GroupName = groupName;
            this.CommissionAmount = commissionAmount;
            this.CommissionAsset = commissionAsset;
            this.Source = source;
        }

        /// <summary>
        /// Commission Time. (unix timestamp).
        /// </summary>
        /// <value>Commission Time. (unix timestamp).</value>
        [DataMember(Name="commission_time")]
        public long CommissionTime { get; set; }

        /// <summary>
        /// User ID.
        /// </summary>
        /// <value>User ID.</value>
        [DataMember(Name="user_id")]
        public long UserId { get; set; }

        /// <summary>
        /// Group name.
        /// </summary>
        /// <value>Group name.</value>
        [DataMember(Name="group_name")]
        public string GroupName { get; set; }

        /// <summary>
        /// Commission Amount.
        /// </summary>
        /// <value>Commission Amount.</value>
        [DataMember(Name="commission_amount")]
        public string CommissionAmount { get; set; }

        /// <summary>
        /// Commission Asset.
        /// </summary>
        /// <value>Commission Asset.</value>
        [DataMember(Name="commission_asset")]
        public string CommissionAsset { get; set; }

        /// <summary>
        /// Source. SPOT - SPOT Rebate, FUTURES - Futures Rebate.
        /// </summary>
        /// <value>Source. SPOT - SPOT Rebate, FUTURES - Futures Rebate.</value>
        [DataMember(Name="source")]
        public string Source { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AgencyCommission {\n");
            sb.Append("  CommissionTime: ").Append(CommissionTime).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  GroupName: ").Append(GroupName).Append("\n");
            sb.Append("  CommissionAmount: ").Append(CommissionAmount).Append("\n");
            sb.Append("  CommissionAsset: ").Append(CommissionAsset).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AgencyCommission);
        }

        /// <summary>
        /// Returns true if AgencyCommission instances are equal
        /// </summary>
        /// <param name="input">Instance of AgencyCommission to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AgencyCommission input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CommissionTime == input.CommissionTime ||
                    this.CommissionTime.Equals(input.CommissionTime)
                ) && 
                (
                    this.UserId == input.UserId ||
                    this.UserId.Equals(input.UserId)
                ) && 
                (
                    this.GroupName == input.GroupName ||
                    (this.GroupName != null &&
                    this.GroupName.Equals(input.GroupName))
                ) && 
                (
                    this.CommissionAmount == input.CommissionAmount ||
                    (this.CommissionAmount != null &&
                    this.CommissionAmount.Equals(input.CommissionAmount))
                ) && 
                (
                    this.CommissionAsset == input.CommissionAsset ||
                    (this.CommissionAsset != null &&
                    this.CommissionAsset.Equals(input.CommissionAsset))
                ) && 
                (
                    this.Source == input.Source ||
                    (this.Source != null &&
                    this.Source.Equals(input.Source))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.CommissionTime.GetHashCode();
                hashCode = hashCode * 59 + this.UserId.GetHashCode();
                if (this.GroupName != null)
                    hashCode = hashCode * 59 + this.GroupName.GetHashCode();
                if (this.CommissionAmount != null)
                    hashCode = hashCode * 59 + this.CommissionAmount.GetHashCode();
                if (this.CommissionAsset != null)
                    hashCode = hashCode * 59 + this.CommissionAsset.GetHashCode();
                if (this.Source != null)
                    hashCode = hashCode * 59 + this.Source.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
