/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// CollateralAdjust
    /// </summary>
    [DataContract]
    public partial class CollateralAdjust :  IEquatable<CollateralAdjust>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollateralAdjust" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CollateralAdjust() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CollateralAdjust" /> class.
        /// </summary>
        /// <param name="orderId">Order ID (required).</param>
        /// <param name="type">Operation types: append - for adding collateral, redeem - for withdrawing collateral (required).</param>
        /// <param name="collaterals">Collateral Currency List.</param>
        public CollateralAdjust(long orderId = default(long), string type = default(string), List<CollateralCurrency> collaterals = default(List<CollateralCurrency>))
        {
            this.OrderId = orderId;
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type", "type is a required property for CollateralAdjust and cannot be null");
            this.Collaterals = collaterals;
        }

        /// <summary>
        /// Order ID
        /// </summary>
        /// <value>Order ID</value>
        [DataMember(Name="order_id")]
        public long OrderId { get; set; }

        /// <summary>
        /// Operation types: append - for adding collateral, redeem - for withdrawing collateral
        /// </summary>
        /// <value>Operation types: append - for adding collateral, redeem - for withdrawing collateral</value>
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// Collateral Currency List
        /// </summary>
        /// <value>Collateral Currency List</value>
        [DataMember(Name="collaterals")]
        public List<CollateralCurrency> Collaterals { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CollateralAdjust {\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Collaterals: ").Append(Collaterals).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CollateralAdjust);
        }

        /// <summary>
        /// Returns true if CollateralAdjust instances are equal
        /// </summary>
        /// <param name="input">Instance of CollateralAdjust to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CollateralAdjust input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OrderId == input.OrderId ||
                    this.OrderId.Equals(input.OrderId)
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Collaterals == input.Collaterals ||
                    this.Collaterals != null &&
                    input.Collaterals != null &&
                    this.Collaterals.SequenceEqual(input.Collaterals)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.OrderId.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Collaterals != null)
                    hashCode = hashCode * 59 + this.Collaterals.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
