/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// Supported borrowing and collateral currencies
    /// </summary>
    [DataContract]
    public partial class CollateralLoanCurrency :  IEquatable<CollateralLoanCurrency>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollateralLoanCurrency" /> class.
        /// </summary>
        /// <param name="loanCurrency">Borrowed currency.</param>
        /// <param name="collateralCurrency">List of supported collateral currencies.</param>
        public CollateralLoanCurrency(string loanCurrency = default(string), List<string> collateralCurrency = default(List<string>))
        {
            this.LoanCurrency = loanCurrency;
            this.CollateralCurrency = collateralCurrency;
        }

        /// <summary>
        /// Borrowed currency
        /// </summary>
        /// <value>Borrowed currency</value>
        [DataMember(Name="loan_currency")]
        public string LoanCurrency { get; set; }

        /// <summary>
        /// List of supported collateral currencies
        /// </summary>
        /// <value>List of supported collateral currencies</value>
        [DataMember(Name="collateral_currency")]
        public List<string> CollateralCurrency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CollateralLoanCurrency {\n");
            sb.Append("  LoanCurrency: ").Append(LoanCurrency).Append("\n");
            sb.Append("  CollateralCurrency: ").Append(CollateralCurrency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CollateralLoanCurrency);
        }

        /// <summary>
        /// Returns true if CollateralLoanCurrency instances are equal
        /// </summary>
        /// <param name="input">Instance of CollateralLoanCurrency to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CollateralLoanCurrency input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LoanCurrency == input.LoanCurrency ||
                    (this.LoanCurrency != null &&
                    this.LoanCurrency.Equals(input.LoanCurrency))
                ) && 
                (
                    this.CollateralCurrency == input.CollateralCurrency ||
                    this.CollateralCurrency != null &&
                    input.CollateralCurrency != null &&
                    this.CollateralCurrency.SequenceEqual(input.CollateralCurrency)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LoanCurrency != null)
                    hashCode = hashCode * 59 + this.LoanCurrency.GetHashCode();
                if (this.CollateralCurrency != null)
                    hashCode = hashCode * 59 + this.CollateralCurrency.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
