/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// FuturesOrderBookItem
    /// </summary>
    [DataContract]
    public partial class FuturesOrderBookItem :  IEquatable<FuturesOrderBookItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FuturesOrderBookItem" /> class.
        /// </summary>
        /// <param name="p">Price (quote currency).</param>
        /// <param name="s">Size.</param>
        public FuturesOrderBookItem(string p = default(string), long s = default(long))
        {
            this.P = p;
            this.S = s;
        }

        /// <summary>
        /// Price (quote currency)
        /// </summary>
        /// <value>Price (quote currency)</value>
        [DataMember(Name="p")]
        public string P { get; set; }

        /// <summary>
        /// Size
        /// </summary>
        /// <value>Size</value>
        [DataMember(Name="s")]
        public long S { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FuturesOrderBookItem {\n");
            sb.Append("  P: ").Append(P).Append("\n");
            sb.Append("  S: ").Append(S).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FuturesOrderBookItem);
        }

        /// <summary>
        /// Returns true if FuturesOrderBookItem instances are equal
        /// </summary>
        /// <param name="input">Instance of FuturesOrderBookItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FuturesOrderBookItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.P == input.P ||
                    (this.P != null &&
                    this.P.Equals(input.P))
                ) && 
                (
                    this.S == input.S ||
                    this.S.Equals(input.S)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.P != null)
                    hashCode = hashCode * 59 + this.P.GetHashCode();
                hashCode = hashCode * 59 + this.S.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
