/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// WithdrawalRecord
    /// </summary>
    [DataContract]
    public partial class WithdrawalRecord :  IEquatable<WithdrawalRecord>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WithdrawalRecord" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WithdrawalRecord() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WithdrawalRecord" /> class.
        /// </summary>
        /// <param name="withdrawOrderId">Client order id, up to 32 length and can only include 0-9, A-Z, a-z, underscore(_), hyphen(-) or dot(.) .</param>
        /// <param name="amount">Currency amount (required).</param>
        /// <param name="currency">Currency name (required).</param>
        /// <param name="address">Withdrawal address.</param>
        /// <param name="failReason">The reason for withdrawal failure is that there is a value when status &#x3D; CANCEL, and the rest of the state is empty.</param>
        /// <param name="timestamp2">The withdrawal end time, i.e.: withdrawal cancel time or withdrawal success time When status &#x3D; CANCEL, the corresponding cancel time When status &#x3D; DONE and block_number &gt; 0, it is the time to withdrawal success.</param>
        /// <param name="memo">Additional remarks with regards to the withdrawal.</param>
        /// <param name="chain">Name of the chain used in withdrawals (required).</param>
        public WithdrawalRecord(string withdrawOrderId = default(string), string amount = default(string), string currency = default(string), string address = default(string), string failReason = default(string), string timestamp2 = default(string), string memo = default(string), string chain = default(string))
        {
            // to ensure "amount" is required (not null)
            this.Amount = amount ?? throw new ArgumentNullException("amount", "amount is a required property for WithdrawalRecord and cannot be null");
            // to ensure "currency" is required (not null)
            this.Currency = currency ?? throw new ArgumentNullException("currency", "currency is a required property for WithdrawalRecord and cannot be null");
            // to ensure "chain" is required (not null)
            this.Chain = chain ?? throw new ArgumentNullException("chain", "chain is a required property for WithdrawalRecord and cannot be null");
            this.WithdrawOrderId = withdrawOrderId;
            this.Address = address;
            this.FailReason = failReason;
            this.Timestamp2 = timestamp2;
            this.Memo = memo;
        }

        /// <summary>
        /// Record ID
        /// </summary>
        /// <value>Record ID</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }

        /// <summary>
        /// Hash record of the withdrawal
        /// </summary>
        /// <value>Hash record of the withdrawal</value>
        [DataMember(Name="txid", EmitDefaultValue=false)]
        public string Txid { get; private set; }

        /// <summary>
        /// 区块编号
        /// </summary>
        /// <value>区块编号</value>
        [DataMember(Name="block_number", EmitDefaultValue=false)]
        public string BlockNumber { get; private set; }

        /// <summary>
        /// Client order id, up to 32 length and can only include 0-9, A-Z, a-z, underscore(_), hyphen(-) or dot(.) 
        /// </summary>
        /// <value>Client order id, up to 32 length and can only include 0-9, A-Z, a-z, underscore(_), hyphen(-) or dot(.) </value>
        [DataMember(Name="withdraw_order_id")]
        public string WithdrawOrderId { get; set; }

        /// <summary>
        /// Operation time
        /// </summary>
        /// <value>Operation time</value>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public string Timestamp { get; private set; }

        /// <summary>
        /// Currency amount
        /// </summary>
        /// <value>Currency amount</value>
        [DataMember(Name="amount")]
        public string Amount { get; set; }

        /// <summary>
        /// fee
        /// </summary>
        /// <value>fee</value>
        [DataMember(Name="fee", EmitDefaultValue=false)]
        public string Fee { get; private set; }

        /// <summary>
        /// Currency name
        /// </summary>
        /// <value>Currency name</value>
        [DataMember(Name="currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Withdrawal address
        /// </summary>
        /// <value>Withdrawal address</value>
        [DataMember(Name="address")]
        public string Address { get; set; }

        /// <summary>
        /// The reason for withdrawal failure is that there is a value when status &#x3D; CANCEL, and the rest of the state is empty
        /// </summary>
        /// <value>The reason for withdrawal failure is that there is a value when status &#x3D; CANCEL, and the rest of the state is empty</value>
        [DataMember(Name="fail_reason")]
        public string FailReason { get; set; }

        /// <summary>
        /// The withdrawal end time, i.e.: withdrawal cancel time or withdrawal success time When status &#x3D; CANCEL, the corresponding cancel time When status &#x3D; DONE and block_number &gt; 0, it is the time to withdrawal success
        /// </summary>
        /// <value>The withdrawal end time, i.e.: withdrawal cancel time or withdrawal success time When status &#x3D; CANCEL, the corresponding cancel time When status &#x3D; DONE and block_number &gt; 0, it is the time to withdrawal success</value>
        [DataMember(Name="timestamp2")]
        public string Timestamp2 { get; set; }

        /// <summary>
        /// Additional remarks with regards to the withdrawal
        /// </summary>
        /// <value>Additional remarks with regards to the withdrawal</value>
        [DataMember(Name="memo")]
        public string Memo { get; set; }

        /// <summary>
        /// Transaction status  - DONE: Completed (block_number &gt; 0 is considered to be truly completed) - CANCEL: Canceled - REQUEST: Requesting - MANUAL: Pending manual review - BCODE: Recharge code operation - EXTPEND: Sent awaiting confirmation - FAIL: Failure on the chain awaiting confirmation - INVALID: Invalid order - VERIFY: Verifying - PROCES: Processing - PEND: Processing - DMOVE: pending manual review - REVIEW: Under review
        /// </summary>
        /// <value>Transaction status  - DONE: Completed (block_number &gt; 0 is considered to be truly completed) - CANCEL: Canceled - REQUEST: Requesting - MANUAL: Pending manual review - BCODE: Recharge code operation - EXTPEND: Sent awaiting confirmation - FAIL: Failure on the chain awaiting confirmation - INVALID: Invalid order - VERIFY: Verifying - PROCES: Processing - PEND: Processing - DMOVE: pending manual review - REVIEW: Under review</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; private set; }

        /// <summary>
        /// Name of the chain used in withdrawals
        /// </summary>
        /// <value>Name of the chain used in withdrawals</value>
        [DataMember(Name="chain")]
        public string Chain { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WithdrawalRecord {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Txid: ").Append(Txid).Append("\n");
            sb.Append("  BlockNumber: ").Append(BlockNumber).Append("\n");
            sb.Append("  WithdrawOrderId: ").Append(WithdrawOrderId).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Fee: ").Append(Fee).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  FailReason: ").Append(FailReason).Append("\n");
            sb.Append("  Timestamp2: ").Append(Timestamp2).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Chain: ").Append(Chain).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WithdrawalRecord);
        }

        /// <summary>
        /// Returns true if WithdrawalRecord instances are equal
        /// </summary>
        /// <param name="input">Instance of WithdrawalRecord to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WithdrawalRecord input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Txid == input.Txid ||
                    (this.Txid != null &&
                    this.Txid.Equals(input.Txid))
                ) && 
                (
                    this.BlockNumber == input.BlockNumber ||
                    (this.BlockNumber != null &&
                    this.BlockNumber.Equals(input.BlockNumber))
                ) && 
                (
                    this.WithdrawOrderId == input.WithdrawOrderId ||
                    (this.WithdrawOrderId != null &&
                    this.WithdrawOrderId.Equals(input.WithdrawOrderId))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Fee == input.Fee ||
                    (this.Fee != null &&
                    this.Fee.Equals(input.Fee))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.FailReason == input.FailReason ||
                    (this.FailReason != null &&
                    this.FailReason.Equals(input.FailReason))
                ) && 
                (
                    this.Timestamp2 == input.Timestamp2 ||
                    (this.Timestamp2 != null &&
                    this.Timestamp2.Equals(input.Timestamp2))
                ) && 
                (
                    this.Memo == input.Memo ||
                    (this.Memo != null &&
                    this.Memo.Equals(input.Memo))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Chain == input.Chain ||
                    (this.Chain != null &&
                    this.Chain.Equals(input.Chain))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Txid != null)
                    hashCode = hashCode * 59 + this.Txid.GetHashCode();
                if (this.BlockNumber != null)
                    hashCode = hashCode * 59 + this.BlockNumber.GetHashCode();
                if (this.WithdrawOrderId != null)
                    hashCode = hashCode * 59 + this.WithdrawOrderId.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.Fee != null)
                    hashCode = hashCode * 59 + this.Fee.GetHashCode();
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.FailReason != null)
                    hashCode = hashCode * 59 + this.FailReason.GetHashCode();
                if (this.Timestamp2 != null)
                    hashCode = hashCode * 59 + this.Timestamp2.GetHashCode();
                if (this.Memo != null)
                    hashCode = hashCode * 59 + this.Memo.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Chain != null)
                    hashCode = hashCode * 59 + this.Chain.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
